- README.md
- controllers/consulta_oferta_academica.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
- swagger/swagger.yml
Se crea el merge de la rama consulta oferta academica a dev donde se encuentra el controlador encargado de realizar la busqueda de las dependencias de servicio OIKOS
> Merge Rama Consulta oferta academica a dev 

- controllers/admision.go
- controllers/archivo_icfes.go
- swagger/swagger.json
- swagger/swagger.yml
Ajuste para realizar update si ya existe el criterio y crear el criterio si no
> Post porcentajes criterios

- controllers/archivo_icfes.go
Verificando funcionalidad registro masivo de notas ICFES https://github.com/udistrital/sga_mid/issues/74
> Ajuste archivo icfes

- controllers/admision.go
- controllers/archivo_icfes.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
Unificando ajustes del módulo de admisiones
> Consulta aspirantes

- controllers/consulta_calendario_proyecto.go
> fix: corrección de url local. 

- controllers/derechos_pecuniarios.go
> fix: Se agrega control de errores en consulta de parámetros.

- controllers/solicitud_docente.go
- controllers/solicitud_produccion.go
se eliminan muestras en consola innecesarias
> fix: se eliminan muestras en consola innecesarias

- controllers/consulta_calendario_academico.go
- controllers/derechos_pecuniarios.go
> fix: correcciones necesarias para el cliente. 

- controllers/consulta_calendario_academico.go
- controllers/crear_actividad_calendario.go
- controllers/derechos_pecuniarios.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: Ajustes modulo de calendario academico
> management: Ajustes modulo de calendario academico

- controllers/inscripciones.go
- controllers/persona.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
Fix: se corrigen los errores de carga de los select, se ajustan funciones post que apuntan al mid, se ajustan funciones get y se crea la funcion de actualizar info_caracteristica
> Fix: correccion de errores en los modulos de informacion basica 

- controllers/consulta_calendario_academico.go
fix: Se cambia api core por api parametros para consulta de periodos de calendarios. udistrital/sga_cliente#296
> fix: Se cambia api core por api parametros

- controllers/consulta_calendario_academico.go
- models/Metadatos.go
fix: ajuste funcion consulta calendario
> fix: ajuste funcion consulta calendario

- controllers/crear_actividad_calendario.go
fix: se corrige la actualización de los responsables (tipo_publico) de una actividad. udistrital/sga_cliente#296
> fix: se corrige la actualizacion de los responsables

- controllers/derechos_pecuniarios.go
- swagger/swagger.json
- swagger/swagger.yml
fix: Ajustes requeridos en controlador derechos_pecuniarios para udistrital/sga_cliente#336
> fix: Ajustes requeridos en controlador derechos_pecuniarios

- models/paquete_solicitud.go
se realiza un ajuste de librerias en modelo de paquete_solicitud
> fix: se realiza un ajuste de librerias en modelo de paquete_solicitud

- controllers/experiencia_laboral.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
fix: ajuste modulo experiencia laboral
> fix: ajuste modulo experiencia laboral

- controllers/formacion.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
Fix: funcion get en formacion academica
> Fix: funcion get en formacion academica

- controllers/experiencia_laboral.go
fix: ajuste creacion experiencia laboral
> fix: ajuste creacion experiencia laboral

- controllers/solicitud_evaluacion.go
- models/solicitud_docente.go
se realiza ajuste en cambio de respuesta en rechazo de evaluacion en formato json
> fix: se realiza ajuste en cambio de respuesta en rechazo de evaluacion

- controllers/clonar_calendario_academico.go
- controllers/experiencia_laboral.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
> fix: ajuste clonar calendario

- controllers/clonar_calendario_academico.go
- controllers/consulta_calendario_academico.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
Fix: correccion de funcion de clonar
> Fix: correccion de funcion de clonar

- controllers/crear_actividad_calendario.go
fix: uniformidad en nombres de propiedades
> fix: uniformidad en nombres de propiedades

- controllers/inscripciones.go
- controllers/persona.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
Fix: creacion de funcion put y correccion funcion get
> Fix: creacion de funcion put y correccion funcion get

- controllers/consulta_calendario_proyecto.go
fix: ajuste consulta proyecto curricular preinscripcion proyecto academico
> fix: ajuste consulta proyecto curricular preinscripcion proyecto academico

- controllers/clonar_calendario_academico.go
- controllers/consulta_calendario_proyecto.go
hotfix: ajuste de preinscripción
> hotfix: ajuste de preinscripción 

- controllers/persona.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
Fix: funcion put en tag de info familiar
> Fix: funcion put en tag de info familiar

- controllers/experiencia_laboral.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
fix: creacion controlador para mostrar informacion de experiencia laboral
> fix: creacion controlador para mostrar informacion de experiencia laboral

- controllers/experiencia_laboral.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
fix: ajuste funcion put experiencia laboral
> fix: ajuste funcion put experiencia laboral

- controllers/formacion.go
- controllers/persona.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: funcion put de formacion academica
> feat: funcion put de formacion academica

- controllers/descuento_academico.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
fix: agregar controlador para consulta de descuentos academicos por descuentos_dependencia
> fix: agregar controlador para consulta de descuentos academicos por descuentos_dependencia

- controllers/descuento_academico.go
- models/paquete_solicitud.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
develop: ajustes de desarrollo
> develop: ajustes de desarrollo 

- conf/app.conf
- controllers/inscripciones.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: funcion que consulta los estados de los recibos y lo envia al cliente con el response indicado
> feat: funcion que consulta los estados de los recibos y lo envia al cliente con el response indicado

- controllers/descuento_academico.go
fix: ajuste rutas descuento academico
> fix: ajuste rutas descuento academico

- controllers/inscripciones.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
fix: ajuste de control de errores cuando un tercero o una inscripcion no existe
> fix: ajuste de control de errores cuando un tercero o una inscripcion no existe

- .env
- Dockerfile
- README.md
- conf/app.conf
- controllers/generar_recibo.go
fix: se ajusta generador de recibos para funcionar en despliegue y se agrega dato de comprobante. udistrital/sga_cliente#417
> fix: se ajusta generador de recibos

- controllers/produccion_academica.go
- controllers/solicitud_docente.go
- models/generacion_alertas.go
- routers/commentsRouter_controllers.go
se realizan ajustes para generación de alertas en algoritmos que hacían falta
> feat: se realizan ajustes para generacion de alertas en algoritmos que

- models/generacion_puntaje.go
Se realiza ajuste en la generación de puntajes ordenando los puntajes para evitar errores
> fix: Se realiza ajuste en la generacion de puntajes ordenando los puntajes

- controllers/generar_recibo.go
fix: se ajusta extension de la imagen que no detectaba. udistrital/sga_cliente#417
> fix: se ajusta extension de la imagen

- controllers/generar_recibo.go
- models/generacion_puntaje.go
hotfix:se ajusta extension de la imagen
> hotfix:se ajusta extension de la imagen

- controllers/generar_recibo.go
- controllers/solicitud_docente.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
hotfix: Ajustes metodo post prueba
> hotfix: Ajustes metodo post prueba 

- controllers/paquete_solicitud.go
- controllers/produccion_academica.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
se ajustan metodos put que no estan funcionando en autenticacion
> fix: se ajustan metodos put que no estan funcionando en autenticacion

- controllers/paquete_solicitud.go
- controllers/produccion_academica.go
- controllers/solicitud_docente.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
hotfix: Ajuste de metodo put a post
> hotfix: Ajuste de metodo put a post

- controllers/admision.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
Feat: función post y get de la evaluación de aspirantes
> Feat: función post y get de la evaluación de aspirantes

- controllers/admision.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
Fix: funcion put que calcula la nota final por aspirante relacionado a un proyecto y a un periodo udistrital/sga_cliente#444
> Fix: funcion put que calcula la nota final por aspirante relacionado a un proyecto y a un periodo udistrital/sga_cliente#444

- controllers/inscripciones.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: Se realiza proceso de inscripción con generación de recibo de pago. #255
> feat: Se realiza proceso de inscripción con generación de recibo

- controllers/consulta_calendario_proyecto.go
fix: Se ajusta uso de parámetro de nivel de formación. udistrital/sga_cliente#455
> fix: Se ajusta uso de parámetro de nivel de formación

- controllers/solicitud_evaluacion.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
Feat: funcion post y get para el manejo de solicitudes de actualizacion de datos udistrital/sga_cliente#459
> Feat: funcion post y get para el manejo de solicitudes de actualizacion de datos udistrital/sga_cliente#459

- controllers/inscripciones.go
fix: se corrigen niveles en generación de inscripción.
> fix: se corrigen niveles en generacion de inscripción.

- controllers/descuento_academico.go
- controllers/produccion_academica.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
fix: ajuste de response de produccion academica cuando no hay informacion udistrital/sga_cliente#465
> fix: ajuste de response de produccion academica cuando no hay informacion udistrital/sga_cliente#465

- controllers/solicitud_evaluacion.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: funcion que consulta las solicitudes, funcion que realiza la trazabilidad de la solicitud udistrital/sga_cliente#476
> feat: funcion que consulta las solicitudes, funcion que realiza la trazabilidad de la solicitud udistrital/sga_cliente#476

- main.go
> fix: incluir auditoria

- .drone.yml
devops: se actualiza archivo drone para despliegue en ambiente de pruebas. #275
> devops: se actualiza archivo drone

- .drone.yml
- main.go
devops: actualización de archivo drone
> Actualización drone

- .drone.yml
devops: modificacion de drone. #275
> devops: modificacion de drone. #275

- controllers/persona.go
- controllers/solicitud_evaluacion.go
feat: funcion post y put que actualizan los datos del estudiante si la solicitud fue aprobada #272
> feat: funcion post y put que actualizan los datos del estudiante si la solicitud fue aprobada #272

- controllers/formacion.go
- controllers/inscripciones.go
- controllers/persona.go
- controllers/produccion_academica.go
fix: ajustes de control de errores de formacion y produccion academica
> fix: ajustes de control de errores de formacion y produccion academica

- controllers/consulta_calendario_academico.go
- controllers/inscripciones.go
Feature ajuste servicio generar recibo
> Feature ajuste servicio generar recibo

- controllers/inscripciones.go
feat: Ajuste de url para consulta y creación de recibos
> feat: Ajuste de url para consulta y creación de recibos

- controllers/crear_proyecto_academico.go
fix: ajustes a peticiones de proyecto académico
> fix: ajustes a peticiones de proyecto academico

- controllers/crear_proyecto_academico.go
- controllers/inscripciones.go
feat: Se ajusta controlador con ajuste del api de proyecto academico
> feat: Se ajusta controlador con ajuste del api de proyecto academico

- controllers/solicitud_evaluacion.go
ajuste de las observaciones de tercero udistrital/sga_cliente/issues/547
> refactor: para issue #547 de sga_client

- controllers/crear_proyecto_academico.go
- controllers/solicitud_evaluacion.go
management: ajuste de consulte de observaciones para la actualización de datos
> management: ajuste de consulte de observaciones para la actualización de datos

- controllers/consulta_calendario_proyecto.go
- controllers/inscripciones.go
- controllers/persona.go
Cambios para dar solución a la issue udistrital/sga_cliente#567
> Ajustes para modulo de admisiones

- controllers/consulta_calendario_proyecto.go
- controllers/inscripciones.go
- controllers/persona.go
- controllers/solicitud_evaluacion.go
> hotfix: Ajustes de servicios 

- controllers/inscripciones.go
Ajuste en la fecha y recibos. udistrital/sga_cliente#567
> Ajuste en la fecha y recibos. udistrital/sga_cliente#567

- controllers/admision.go
- controllers/descuento_academico.go
Ajustes para cumplimiento de la issue. udistrital/sga_cliente#571
> Ajustes para cumplimiento de la issue.udistrital/sga_cliente#571

- controllers/admision.go
- controllers/descuento_academico.go
- controllers/inscripciones.go
hotfix: Ajustes para cumplimiento de la issue.udistrital/sga_cliente#571
> hotfix: Ajustes para cumplimiento de la issue.udistrital/sga_cliente#571

- controllers/admision.go
fix: ajuste a variable. udistrital/sga_cliente#571
> fix: ajuste a variable. udistrital/sga_cliente#571

- controllers/admision.go
- controllers/descuento_academico.go
> hotfix: ajuste a variable.

- controllers/persona.go
- controllers/solicitud_evaluacion.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
Ajustes para adaptarse al nuevo flujo en las solicitudes udistrital/sga_cliente#585
> Ajustes para adaptarse al nuevo flujo en las solicitudes

- controllers/admision.go
- controllers/persona.go
- controllers/solicitud_evaluacion.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: Ajustes de desarrollo para le flujo de solicitudes
> management: Ajustes de desarrollo para le flujo de solicitudes

- controllers/consulta_calendario_proyecto.go
Ajuste en la consultas de consulta_calendario_proyecto/nivel udistrital/sga_cliente#562
> Ajuste en la consultas de consulta_calendario_proyecto/nivel udistrital/sga_cliente#562

- controllers/formacion.go
fix: ajuste de universidad no encontrada. udistrital/sga_cliente#636
> fix: ajuste de universidad no encontrada. udistrital/sga_cliente#636

- controllers/admision.go
- controllers/solicitud_evaluacion.go
fix: Ajustes en la aprobación de solicitudes y obtención de datos de solicitud. udistrital/sga_cliente#606
> fix: Ajustes en la aprobación de solicitudes y obtención de datos de solicitud

- controllers/formacion.go
feat: ajuste de documentos de información académica. #308
> feat: ajuste de documentos de información académica. #308

- controllers/derechos_pecuniarios.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: Creación de recibos pecuniarios. udistrital/sga_cliente#664
> feat: Creación de recibos pecuniarios. udistrital/sga_cliente#664

- controllers/derechos_pecuniarios.go
- controllers/formacion.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: creación método generar recibo derecho
> management: creación método generar recibo derecho 

- controllers/derechos_pecuniarios.go
- controllers/generar_recibo.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: Generación de recibos de derechos pecuniarios. udistrital/sga_cliente#671
> feat: Generación de recibos de derechos pecuniarios. udistrital/sga_cliente#671

- controllers/persona.go
feat: ajuste para guardado del documento de discapacidad . #313
> feat: ajuste para guardado del documento de discapacidad . #313

- .drone.yml
hotfix: ajuste de step run_test_go
> hotfix: ajuste de step run_test_go

- controllers/experiencia_laboral.go
- controllers/formacion.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: ajustes en CRUD para experiencia laboral y formación académica. udistrital/sga_cliente#701
> feat: ajustes en CRUD para experiencia laboral y formación academica. udistrital/sga_cliente#701

- controllers/experiencia_laboral.go
- controllers/formacion.go
- controllers/persona.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
hotfix: Ajustes de métodos CRUD módulos de experiencia laboral y académica
> hotfix: Ajustes de métodos CRUD módulos de experiencia laboral y académica 

- controllers/derechos_pecuniarios.go
- controllers/inscripciones.go
feat: Ajuste para toma de año en recibo de inscripción y de derecho pecuniario. udistrital/sga_cliente#732
> feat: Ajuste para toma de año en recibo de inscripción y de derecho pecuniario. udistrital/sga_cliente#732

- controllers/persona.go
feat: Ajuste al nuevo modelo de soporte documental. udistrital/sga_cliente#744
> feat: Ajuste al nuevo modelo de soporte documental. udistrital/sga_cliente#744

- conf/app.conf
- controllers/practicas_academicas.go
- models/SendJsonHeader.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
- swagger/swagger.yml
feat: Creación de controlador de prácticas académicas con integración del nuevo gestor documental. udistrital/sga_cliente#743
> feat: Creación de controlador de prácticas académicas con integración del nuevo gestor documental. udistrital/sga_cliente#743

- conf/app.conf
- controllers/persona.go
- controllers/practicas_academicas.go
- models/SendJsonHeader.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
- swagger/swagger.yml
management: Creación de controlador de prácticas académicas con integración del nuevo gestor documental. udistrital/sga_cliente#743 #336
> management: Creación de controlador de prácticas académicas con integración del nuevo gestor documental. udistrital/sga_cliente#743 #336

- controllers/practicas_academicas.go
- swagger/swagger.json
- swagger/swagger.yml
feat: Funcionalidad de consulta de prácticas académicas. udistrital/sga_cliente#768
> feat: Funcionalidad de consulta de prácticas académicas. udistrital/sga_cliente#768

- controllers/practicas_academicas.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: Ajustes de build y desarrollo de funcionalidad parcial de practicas académica
> management: Ajustes de build y desarrollo de funcionalidad parcial de practicas académica 

- controllers/solicitud_docente.go
- models/produccion_academica.go
- models/solicitud_docente.go
- swagger/swagger.json
- swagger/swagger.yml
feat: ajustes en gets de producción académica docente. udistrital/sga_cliente#806
> feat: ajustes en gets de producción académica docente. udistrital/sga_cliente#806

- conf/app.conf
- controllers/derechos_pecuniarios.go
- controllers/inscripciones.go
hotfix: Ajustes de variables de entorno para consulta y generación de recibos en test y prod
> hotfix: Ajustes de variables de entorno para consulta y generación de recibos en test y prod

- controllers/inscripciones.go
feat: ajuste en respuesta de información complementaria. udistrital/sga_cliente#819
> feat: ajuste en respuesta de información complementaria. udistrital/sga_cliente#819

- controllers/inscripciones.go
hotfix: ajuste en respuesta de información de contacto. udistrital/sga_cliente#819
> hotfix: ajuste en respuesta de información de contacto. udistrital/sga_cliente#819

- controllers/practicas_academicas.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: funcionalidad de envió de invitaciones a prácticas académicas. udistrital/sga_cliente#776
> feat: funcionalidad de envió de invitaciones a prácticas académicas. udistrital/sga_cliente#776 

- controllers/inscripciones.go
- controllers/practicas_academicas.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: Ajuste de funcionalidad de invitación a prácticas a académicas. udistrital/sga_cliente#776
> management: Ajuste de funcionalidad de invitación a prácticas a académicas. udistrital/sga_cliente#776

- controllers/experiencia_laboral.go
- controllers/formacion.go
fix: formato de nit para empresas e instituciones
> fix: formato de nit para empresas e instituciones

- controllers/formacion.go
> fix: consulta de nit

- controllers/experiencia_laboral.go
- controllers/formacion.go
> management: búsqueda de nit

- controllers/experiencia_laboral.go
- controllers/formacion.go
fix: consulta de nit experiencia laboral
> fix: consulta de nit experiencia laboral

- controllers/experiencia_laboral.go
- controllers/formacion.go
management: ajustes de formato a búsqueda de nit experiencia laboral
> management: ajustes de formato a búsqueda de nit experiencia laboral

- controllers/practicas_academicas.go
feat: desarrollo de la funcionalidad para el informe de prácticas académicas. udistrital/sga_cliente#788
> feat: desarrollo de la funcionalidad para el informe de prácticas académicas. udistrital/sga_cliente#788

- controllers/derechos_pecuniarios.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: ajustes en derechos pecuniarios para obtener datos de solicitud. udistrital/sga_cliente#808
> feat: ajustes en derechos pecuniarios para obtener datos de solicitud. udistrital/sga_cliente#808

- controllers/derechos_pecuniarios.go
- controllers/practicas_academicas.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: cambios en derechos_pecuniarios
> management: cambios en derechos_pecuniarios

- controllers/derechos_pecuniarios.go
- controllers/practicas_academicas.go
- models/gestor_documental.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: ajustes en consulta de derechos pecuniarios. udistrital/sga_cliente#810
> feat: ajustes en consulta de derechos pecuniarios. udistrital/sga_cliente#810

- controllers/derechos_pecuniarios.go
- controllers/practicas_academicas.go
- models/gestor_documental.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: ajustes en consulta de derechos pecuniarios.
> management: ajustes en consulta de derechos pecuniarios. 

- controllers/derechos_pecuniarios.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: Generación de solicitud de derecho pecuniario. udistrital/sga_cliente#813
> feat: Generación de solicitud de derecho pecuniario. udistrital/sga_cliente#813

- controllers/derechos_pecuniarios.go
- controllers/generar_recibo.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: Integración de consulta de solicitudes de derechos pecuniarios. udistrital/sga_cliente#814
> feat: Integración de consulta de solicitudes de derechos pecuniarios. udistrital/sga_cliente#814

- controllers/derechos_pecuniarios.go
- controllers/generar_recibo.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: Integración de consulta de solicitudes de derechos pecuniarios. udistrital/sga_cliente#814
> management: Integración de consulta de solicitudes de derechos pecuniarios. udistrital/sga_cliente#814

- controllers/derechos_pecuniarios.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: respuesta de solicitudes de derechos pecuniarios. udistrital/sga_cliente#815
> feat: respuesta de solicitudes de derechos pecuniarios. udistrital/sga_cliente#815

- controllers/derechos_pecuniarios.go
fix: ajuste de respuesta . udistrital/sga_cliente#817
> fix: ajuste de respuesta . udistrital/sga_cliente#817

- controllers/transferencia_reintegro.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
- swagger/swagger.yml
feat: creación de modulo para gestión de inscripciones de transferencia y reingresos. udistrital/sga_cliente#858
> feat: creación de modulo para gestión de inscripciones de transferencia y reingresos. udistrital/sga_cliente#858

- controllers/derechos_pecuniarios.go
- controllers/transferencia_reintegro.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
- swagger/swagger.yml
management: creación de modulo para gestión de inscripciones de transferencia y reingresos. udistrital/sga_cliente#858
> management: creación de modulo para gestión de inscripciones de transferencia y reingresos. udistrital/sga_cliente#858

- controllers/derechos_pecuniarios.go
- controllers/inscripciones.go
- controllers/transferencia_reingreso.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
- swagger/swagger.yml
feat: Consulta de transferencias y reingreso. udistrital/sga_cliente#859
> feat: Consulta de transferencias y reingreso. udistrital/sga_cliente#859

- controllers/derechos_pecuniarios.go
- controllers/inscripciones.go
- controllers/transferencia_reingreso.go
- controllers/transferencia_reintegro.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
- swagger/swagger.yml
hotfix: Consulta de transferencias y reingreso. udistrital/sga_cliente#859 #374
> hotfix: Consulta de transferencias y reingreso. udistrital/sga_cliente#859 #374

- controllers/transferencia_reingreso.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: Integración de servicio de consulta de inscripciones. udistrital/sga_cliente#859
> feat: Integración de servicio de consulta de inscripciones. udistrital/sga_cliente#859

- controllers/practicas_academicas.go
fix: ajustes en la consulta de registros de practicas académicas. udistrital/sga_cliente#898
> fix: ajustes en la consulta de registros de practicas académicas. udistrital/sga_cliente#898

- conf/app.conf
hotfix: ajustes en la consulta de registros de practicas académicas. udistrital/sga_cliente#898 #380
> hotfix: ajustes en la consulta de registros de practicas académicas. udistrital/sga_cliente#898 #380

- conf/app.conf
- controllers/practicas_academicas.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: integración del servicio de espacios académicos. udistrital/sga_cliente#898
Es necesario agregar la variable EspaciosAcademicosService = pruebasapi2.intranetoas.udistrital.edu.co:8530/ para integrar los servicios de la API de espacios académicos
> feat: integración del servicio de espacios académicos. udistrital/sga_cliente#898

- controllers/experiencia_laboral.go
- controllers/formacion.go
- controllers/inscripciones.go
- controllers/persona.go
- controllers/practicas_academicas.go
- controllers/transferencia_reingreso.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: integración de inscripción de transferencias y reingresos. udistrital/sga_cliente#860
> feat: integración de inscripción de transferencias y reingresos. udistrital/sga_cliente#860

- conf/app.conf
- controllers/experiencia_laboral.go
- controllers/formacion.go
- controllers/inscripciones.go
- controllers/persona.go
- controllers/practicas_academicas.go
- controllers/transferencia_reingreso.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: integración de inscripción de transferencias y reingresos. udistrital/sga_cliente#860
> management: integración de inscripción de transferencias y reingresos. udistrital/sga_cliente#860 

- controllers/derechos_pecuniarios.go
- controllers/transferencia_reingreso.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: ajustes para la respuesta de transferencias y reingresos. udistrital/sga_cliente#863
> feat: ajustes para la respuesta de transferencias y reingresos. udistrital/sga_cliente#863

- controllers/derechos_pecuniarios.go
- controllers/transferencia_reingreso.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
mangement: ajustes para la respuesta de transferencias y reingresos. udistrital/sga_cliente#863
> mangement: ajustes para la respuesta de transferencias y reingresos. udistrital/sga_cliente#863

- controllers/derechos_pecuniarios.go
- controllers/transferencia_reingreso.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: feat: Funcionalidad de actualizar solicitud de transferencia. udistrital/sga_cliente#863
> management: feat: Funcionalidad de actualizar solicitud de transferencia. udistrital/sga_cliente#863

- controllers/transferencia_reingreso.go
fix: error de dato faltante en transferencias. udistrital/sga_cliente#864
> fix: error de dato faltante en transferencias. udistrital/sga_cliente#864

- controllers/crear_proyecto_academico.go
- controllers/derechos_pecuniarios.go
- controllers/transferencia_reingreso.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: ajustes de seguridad. udistrital/sga_cliente#917
> management: ajustes de seguridad. udistrital/sga_cliente#917

- controllers/consulta_calendario_academico.go
- controllers/transferencia_reingreso.go
- routers/router.go
- swagger/swagger.json
- swagger/swagger.yml
fix: correcciones de calendario académico y error en transferencias. udistrital/sga_cliente#913
> fix: correcciones de calendario académico y error en transferencias. udistrital/sga_cliente#913

- controllers/admision.go
fix: Ajuste de respuesta para admision/postcupos. udistrital/sga_cliente#911
> fix: Ajuste de respuesta para admision/postcupos. udistrital/sga_cliente#911

- controllers/admision.go
- controllers/inscripciones.go
hotfix: ajuste de carga de recibos de inscripción
> hotfix: ajuste de carga de recibos de inscripción 

- controllers/derechos_pecuniarios.go
- swagger/swagger.json
- swagger/swagger.yml
fix: ajustes de seguridad en derechos pecuniarios. udistrital/sga_cliente#914
> fix: ajustes de seguridad en derechos pecuniarios. udistrital/sga_cliente#914

- controllers/transferencia_reingreso.go
fix: ajuste en tipo de solicitud de transferencia
> fix: ajuste en tipo de solicitud de transferencia

- controllers/transferencia_reingreso.go
fix: carga de elementos cuando no se tiene un código de estudiante en transferencias. udistrital/sga_cliente#864
> fix: carga de elementos cuando no se tiene un código de estudiante en transferencias. udistrital/sga_cliente#864

- controllers/transferencia_reingreso.go
hotfix: carga de elementos cuando no se tiene un código de estudiante en transferencias. udistrital/sga_cliente#864 #413
> hotfix: carga de elementos cuando no se tiene un código de estudiante en transferencias. udistrital/sga_cliente#864 #413

- controllers/transferencia_reingreso.go
fix: ajuste de respuesta en calendario de transferencias. udistrital/sga_cliente#864
> fix: ajuste de respuesta en calendario de transferencias

- controllers/transferencia_reingreso.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
fix: ajustes para bugs en transferencias externas. udistrital/sga_cliente#864
> fix: ajustes para bugs en transferencias externas. udistrital/sga_cliente#864

- controllers/notas.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
GetEstadosRegistros(): funcion que retorna los estados de los registros de notas de todas las asignaturas para determinado periodo.
-  fix: se retiran datos quemados que emulan plan_estudio, ahora se consulta periodo_id
> feat: funcionalidad obtener Estados Registros de notas for issue #970

- controllers/notas.go
- controllers/transferencia_reingreso.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: for issue #971 funcionalidad listar notas parciales para estudiante. #423
> management: for issue #971 funcionalidad listar notas parciales para estudiante. #423

- controllers/persona.go
fix: Ajustes en la información complementaria. udistrital/sga_cliente#864
> fix: Ajustes en la información complementaria. udistrital/sga_cliente#864

- controllers/notas.go
- controllers/persona.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: for issue #984, ajustes para calculo definitiva y cierre calificaciones
> management: for issue #984, ajustes para calculo definitiva y cierre calificaciones

- controllers/inscripciones.go
- controllers/produccion_academica.go
hotfix: Ajuste para respuesta en consulta a produccion academica
> hotfix: Ajuste para respuesta en consulta a produccion academica 

- controllers/inscripciones.go
- controllers/produccion_academica.go
hotfix: Ajuste para respuesta en consulta a produccion academica
> hotfix: Ajuste para respuesta en consulta a produccion academica

- controllers/clonar_calendario_academico.go
- controllers/consulta_calendario_academico.go
- controllers/produccion_academica.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: for issues #997 #999, funcionalidad consulta calendario info extension y clon calendario extension
> management: for issues #997 #999, funcionalidad consulta calendario info extension y clon calendario extension

- controllers/experiencia_laboral.go
- controllers/formacion.go
- swagger/swagger.yml
hotfix: Ajuste de consulta id para controladores de formación y experencia por inconsitencia en id de ambiente de prod
> hotfix: Ajuste de consulta id para controladores de formación y experencia por inconsitencia en id de ambiente de prod

- controllers/experiencia_laboral.go
- controllers/formacion.go
hotfix: ajuste de consulta de formción academica y experencia sin id para sincronizar con producción
> hotfix: ajuste de consulta de formción academica y experencia sin id para sincronizar con producción

- controllers/persona.go
- routers/commentsRouter_controllers.go
- swagger/swagger.yml
- Ajuste de guardado en creación tercero, se añade Orientacion sexual e identidad de genero como información complementaria.
- Ajuste de consulta de tercero, se añade consulta a información complementaria de Orientacion sexual e identidad de género.
_Nota: `bee run` automáticamente editó commentsRouter y swagger pero no afecta ni rutas ni funcionamiento._
> feat: #1079 ajuste guardado y consulta tercero

- controllers/persona.go
- routers/commentsRouter_controllers.go
- Se añade función `ConsultarExistenciaPersona()` para verificar la existencia de tercero en base de datos, busqueda por numero documento.
- ruta: **persona/existe_persona/:numeroDocumento** método GET
- Se añade función `ActualizarPersona()` para relación la información complementaria del tercero como el Id del tercero en existencia.
- ruta: **persona/actualizar_persona** método PUT
> feat: udistrital/sga_cliente#1085 Nuevas funcionalidades consuta, actualizacion tercero

- controllers/descuento_academico.go
- controllers/experiencia_laboral.go
- controllers/formacion.go
- controllers/inscripciones.go
- controllers/produccion_academica.go
- Se ajusta las funciones relacionadas con inscripciones para Inactivar registros en vez de eliminarlos, a su vez se ajustan las consultas para tener en cuenta el Activo:true
> feat: udistrital/sga_cliente#1086 cambio DELETE por PUT, add Activo:true

- controllers/inscripciones.go
- controllers/persona.go
- models/obtener_id.go
> udistrital/sga_cliente#1091 funcionalidad GET POST PUT info_complementaria contacto

- controllers/consulta_calendario_proyecto.go
> udistrital/sga_cliente#1093 inclusión consulta fecha cierre inscripcion

- controllers/persona.go
- Se ajusta respuesta controlador persona/guardar_persona método POST udistrital/sga_cliente#912
> fix: udistrital/sga_cliente#912 Ajuste respueta controladores persona

- controllers/consulta_calendario_proyecto.go
- controllers/persona.go
hotfix: udistrital/sga_cliente#912 Ajuste respueta controladores persona
> hotfix: udistrital/sga_cliente#912 Ajuste respueta controladores persona

- controllers/formacion.go
- controllers/inscripciones.go
- https://github.com/udistrital/sga_cliente/issues/1103
- Ajuste de consulta GetEstadoInscripcion() para retornar el estado de inscripción que se carga en la tabla de recibos
- En adición se ajusta GetFormacionAcademicaByTercero() para carga correcta de formación académica (tiene encuenta cargade proyectos service y parametros service)
> feat: udistrital/sga_cliente#1103 ajuste controlador inscripciones y formacion_academica

- controllers/formacion.go
- controllers/inscripciones.go
- controllers/persona.go
management: udistrital/sga_cliente#1103 ajuste controlador inscripciones y formacion_academica #464
> management: udistrital/sga_cliente#1103 ajuste controlador inscripciones y formacion_academica #464

- controllers/experiencia_laboral.go
- controllers/formacion.go
- Se quita Activo a consulta de universidad
- Se ajusta el formato de consulta por número nit de empresa en exp laboral
> fix: ajuste consultas formacion_academica & experiencia_laboral

- controllers/experiencia_laboral.go
- controllers/formacion.go
- controllers/inscripciones.go
hotfix: ajuste consultas formacion_academica & experiencia_laboral
> hotfix: ajuste consultas formacion_academica & experiencia_laboral

- controllers/experiencia_laboral.go
- issue: Hay algunos registros que el campo Nit de empresa se están guardando como String y en otros como número, si vienen como número Go los trata como float64
- fix: se verifica primero el tipo de dato, si es float se pasa a string.
> fix: Ajuste consulta experiencia laboral

- controllers/experiencia_laboral.go
- controllers/formacion.go
hotfix: Ajuste consulta experiencia laboral
> hotfix: Ajuste consulta experiencia laboral

- controllers/persona.go
- https://github.com/udistrital/sga_cliente/issues/1108
- Se ajusta consulta para retornar telefono tambien
- Se ajusta guardado para almacernar telefono principal
> feat: udistrital/sga_cliente#1108 AJustes consulta y guardado info persona

- controllers/experiencia_laboral.go
- controllers/formacion.go
- controllers/persona.go
hotfix: remuve de query campo activo en consulta terceroUniversidad y empresa
> hotfix: remuve de query campo activo en consulta terceroUniversidad y empresa

- controllers/formacion.go
- Se ajusta el controlador de consulta para traer el programa ya sea en parámetros o proyectoAcadémico, ya si no encuentra ninguno si va a fallar.
> fix: Ajuste consulta programa en formacion_academica

- controllers/experiencia_laboral.go
- controllers/formacion.go
hotfix: Ajuste consulta programa en formacion_academica
> hotfix: Ajuste consulta programa en formacion_academica 

- controllers/experiencia_laboral.go
- controllers/formacion.go
hotfix: ajuste consultas empresa/universidad por nit
> hotfix: ajuste consultas empresa/universidad por nit

- controllers/experiencia_laboral.go
- controllers/formacion.go
hotfix: Dejar consulta de ubicación nula si la universidad no tiene ubicación.
> hotfix: Dejar consulta de ubicación nula si la universidad no tiene ubicación.

- controllers/formacion.go
- controllers/persona.go
hotfix:ajustes de consulta de exclusión de carnet estudiantil
> hotfix:ajustes de consulta de exclusión de carnet estudiantil 

- controllers/admision.go
- controllers/experiencia_laboral.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
management: udistrital/sga_cliente#1146 desarrollo consulta lista aspirantes para distintas tablas
> management: udistrital/sga_cliente#1146 desarrollo consulta lista aspirantes para distintas tablas

- controllers/admision.go
- controllers/derechos_pecuniarios.go
- controllers/inscripciones.go
- controllers/transferencia_reingreso.go
- models/verificar_fechas.go
management: udistrital/sga_cliente#1169 add estado pago recibo inscripción lista aspirantes
> management: udistrital/sga_cliente#1169 add estado pago recibo inscripción lista aspirantes

- controllers/persona.go
- Se añade telefono al post de guardar personsa, hacía falta.
- Se añade telefono a consulta si existe persona, hacía falta.
> feat: udistrital/sga_cliente#1179 inclusión teléfono en consultas

- controllers/consulta_calendario_academico.go
- controllers/generar_recibo.go
hotfix: tiene en cuenta si idPeriodo es cero
> hotfix: tiene en cuenta si idPeriodo es cero

- controllers/admision.go
- controllers/produccion_academica.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
- https://github.com/udistrital/sga_cliente/issues/1215
- Se añade a la consulta de evaluación de documentos el estado de "INSCRITO con Observación" Id: 6
- fix: ajuste cambio de método en producción_académica estaba POST, pero es PUT, require actualización de swagger.
> feat: udistrital/sga_cliente#1215 add_list_inscrito_con_observación

- controllers/admision.go
- controllers/consulta_calendario_academico.go
- controllers/produccion_academica.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
hotfix: udistrital/sga_cliente#1215 add_list_inscrito_con_observación
> hotfix: udistrital/sga_cliente#1215 add_list_inscrito_con_observación

- .drone.yml
- .gitignore
- controllers/admision.go
- controllers/produccion_academica.go
- controllers/time_bog.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
- swagger/swagger.yml
management: udistrital/sga_cliente#1238 add controller get_time_bogota
> management: udistrital/sga_cliente#1238 add controller get_time_bogota

- controllers/admision.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
- https://github.com/udistrital/sga_cliente/issues/1237
- Desarrollo de controlador que consulta la dependencia asociada a tercero mediante vinculación.
- Se verifica si los ids son válidos
- **Requiere update de swagger**
> feat: udistrital/sga_cliente#1237 controlador get dependencia por vinculación tercero

- controllers/admision.go
- controllers/descuento_academico.go
- controllers/experiencia_laboral.go
- controllers/produccion_academica.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
- https://github.com/udistrital/sga_cliente/issues/1256
- Solo requiere ajuste y habilitación del put de descuento académico
- **Requiere actualizar swagger** ⚠️ 
Adición:
- Se corrigen detalles como:
- en post de cupos, se filtra también por periodo,
- en put de experiencia laboral, corrección tipo de dato nit
- en delete de producción académica, ya ese delete se encarga de desactivar el campo Activo y no borrar
> feat: udistrital/sga_cliente#1256 ajuste PUT descuento check PUT produccionAcademica

- controllers/admision.go
- controllers/descuento_academico.go
- controllers/experiencia_laboral.go
- controllers/produccion_academica.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
managment: udistrital/sga_cliente#1256 ajuste PUT descuento check PUT produccionAcademica
> managment: udistrital/sga_cliente#1256 ajuste PUT descuento check PUT produccionAcademica

- controllers/plan_trabajo_docente.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: Creación de endpoints para manejo de planes de trabajo docente. udistrital/sga_cliente#1286
> feat: Creación de endpoints para manejo de planes de trabajo docente. udistrital/sga_cliente#1286

- controllers/plan_trabajo_docente.go
feat: ajuste para guardar y consultar la información de los planes de docentes. udistrital/sga_cliente#1299
> feat: ajuste para guardar y consultar la información de los planes de docentes. udistrital/sga_cliente#1299

- controllers/plan_trabajo_docente.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: creación de controlador de disponibilidad espacio físico udistrital/sga_cliente#1300
> feat: creación de controlador de disponibilidad espacio físico udistrital/sga_cliente#1300

- conf/app.conf
- controllers/plan_trabajo_docente.go
fix: se agrega variable para api de plan trabajo docente
> fix: se agrega variable para api de plan trabajo docente

- controllers/plan_trabajo_docente.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
feat: ajuste en controlador de disponibilidad de espacio físico. udistrital/sga_cliente#1308
> feat: ajuste en controlador de disponibilidad de espacio físico. udistrital/sga_cliente#1308

- controllers/plan_trabajo_docente.go
fix: Ajuste para consultar la información de actividades en planes de trabajo docente. udistrital/sga_cliente#1297
> fix: Ajuste para consultar la información de actividades en planes de trabajo docente. udistrital/sga_cliente#1297

- controllers/espacios_academicos.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
- swagger/swagger.yml
- https://github.com/udistrital/sga_cliente/issues/1309
- Nuevo controlador para consulta de espacios academicos por proyecto.
- consulta espacios requeridos, y da formato para usar en tabla cliente
- Requiere actualizar swagger ⚠️
> feat: udistrital/sga_cliente#1309 controlador consulta espacios academicos por proyecto

- controllers/espacios_academicos.go
- controllers/plan_trabajo_docente.go
- routers/commentsRouter_controllers.go
- routers/router.go
- swagger/swagger.json
- swagger/swagger.yml
managment:  udistrital/sga_cliente#1309 controlador consulta espacios academicos por proyecto
> managment:  udistrital/sga_cliente#1309 controlador consulta espacios academicos por proyecto

- controllers/error.go
- controllers/plan_trabajo_docente.go
- models/data/plan_trabajo_docente.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
- utils/checkParams.go
- utils/filter.go
- utils/requestManager/requests.go
- utils/requestManager/responses_format.go
- https://github.com/udistrital/sga_cliente/issues/1316
- Creación de controlador para copia de plan trabajo docente para periodos académicos anteriores.
- Copia de carga lectiva solamente, pendiente actividades.
- Requiere actualizar swagger ⚠️ 
Nota: **Mejoras a mid**
- Manejo de respuesta de error cuando Mid falla, retorna Internal Server Error
- Se crean utilidades como conversión de data en base a modelo de datos para simplificar el uso de interfaces, funcionalidades para filtrado en arrays
- Se construye un nuevo sistema de peticiones para simplificar el flujo de manejo de errores y respuesta; en desarrollo manejo de peticiones asíncronas con goroutines
> feat: udistrital/sga_cliente#1316 controlador copiar plan trabajo docente

- controllers/inscripciones.go
hotfix: ajuste de valor campo tipo_recibo para solucionar problema pago recibos banco
> hotfix: ajuste de valor campo tipo_recibo para solucionar problema pago recibos banco

- controllers/generar_recibo.go
- ⚠️ Test codificación EAN código barras recibo banco
> Fix: cambio codificacion barcode

- controllers/generar_recibo.go
- controllers/inscripciones.go
hotfix: cambio codificacion barcode
> hotfix: cambio codificacion barcode

- controllers/plan_trabajo_docente.go
- models/data/espacios_academicos.go
- utils/filter.go
- https://github.com/udistrital/sga_cliente/issues/1325
- Se refactoriza el controlador para mejor manejo de la copia de la carga lectiva.
- Se añade la copia de carga de actividades
- Se ajusta el put de guardado del plan trabajo docente para descartar lo que no va cuando se hace la copia
> feat: udistrital/sga_cliente#1325 ajuste controlador copia actividades

- controllers/plan_trabajo_docente.go
-  https://github.com/udistrital/sga_cliente/issues/1326
- Se ajustan controladores para manejo de flujo en edición y aprobación de plan trabajo docente
> feat: udistrital/sga_cliente#1326 ajuste flujo plan trabajo docente

- controllers/generar_recibo.go
- https://github.com/udistrital/sga_cliente/issues/1330
- Se ajusta la secuencia numérica del código de barras para separación automática en lectura con escáner de acuerdo a GS1-128
- Se agranda un poco el grafico del código de barras
> feat: udistrital/sga_cliente#1330 mejora codificación codigo barras recibo banco

- controllers/generar_recibo.go
managment: ajuste de controlador de codigo de barras y estados plan docente
> managment: ajuste de controlador de codigo de barras y estados plan docente 

- controllers/espacios_academicos.go
Actualizado controlador PutAcademicSpaceAssignPeriod para creación de grupos para espacio académico padre sin hijos, y control de retorno es respuesta del endpoint.
> fix: udistrital/sga_cliente#1341 updated PutAcademicSpaceAssignPeriod controller to create groups to empty parent

- controllers/plan_trabajo_docente.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
- https://github.com/udistrital/sga_cliente/issues/1367
- ⚠️ **Requiere actualizar swagger**
> feat: udistrital/sga_cliente#1367 listar planes preaprobados verificacion ptd

- controllers/plan_trabajo_docente.go
- controllers/reportes.go
- utils/xlsx2pdf/converter.go
- nota: prints temporales debug reportes
> fix: ajuste lista Verificacion PTD add aprobados/noaprov

- controllers/plan_trabajo_docente.go
- controllers/reportes.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
- utils/xlsx2pdf/converter.go
- https://github.com/udistrital/sga_cliente/issues/1373
- Construcción de selects: Sede > Edificio > Salon en base a dependencia dada y la fecha actual.
- El controlador recupera los espacios físicos asignados a una dependencia(proyecto), además tiene en cuenta que se encuentre dentro de las fechas de asignación.
- Se navega el árbol de relación desde el espacio tipo salon hasta llegar a la sede, (si hay relaciones intermedias las navega pero no las tiene en cuenta)
- ⚠️ **Update Swagger**
> feat: udistrital/sga_cliente#1373 Controlador EspaciosFisicos Dependencia

- conf/app.conf
- controllers/plan_trabajo_docente.go
udistrital/sga_cliente#1402
- Se modifica el almacenamiento de la carga para almacenar en el api de horarios en la tabla de colocación el horario y el espacio físico
- Se modifica la secuencia de consultas para obtener los datos de horarios y espacios físicos requeridos en la reconstrucción del objeto requerido para el cliente en la presentación del plan docente y su correspondiente carga
> feat: actualizadas funciones de actualización y consulta de carga plan desde la API horarios

- controllers/plan_trabajo_docente.go
udistrital/sga_cliente#1402
Se agrega lógica para no procesar los antiguos registros de cargas de los planes actuales, así se evitan errores en cliente al no encontrar la estructura del horario.
>  feat: ajuste campos de espacio fisico y exclusión antiguos registros

- conf/app.conf
- controllers/plan_trabajo_docente.go
management: ajuste campos de espacio fisico y exclusión antiguos registros
> management: ajuste campos de espacio fisico y exclusión antiguos registros 

- conf/app.conf
- controllers/espacios_academicos.go
- helpers/utilidades.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
udistrital/sga_cliente#1417 Creada función con estructura requerida para llenar el documento del syllabus
udistrital/sga_cliente#1441 Consultado idiomas para agregarlo al documento del syllabus
> feat: Creada función para construir la estructura de datos para la plantilla del documento syllabus

- controllers/espacios_academicos.go
- controllers/plan_estudios.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
- utils/dependencias_query_functions.go
- utils/map_functions.go
udistrital/sga_cliente#1431
Controlador que genera el json requerido para la creación de la vista de plan de estudios y el documento PDF
> feat: udistrital/sga_cliente#1431 Creado controlador para visualización de planes de estudio

- controllers/espacios_academicos.go
- controllers/plan_estudios.go
- helpers/utilidades.go
hotfix: agregada función default value para maps
> hotfix: agregada función default value para maps

- controllers/espacios_academicos.go
- helpers/utilidades.go
management: udistrital/sga_cliente#1455 Actualizado controlador datos de la plantilla
> management: udistrital/sga_cliente#1455 Actualizado controlador datos de la plantilla

- controllers/plan_trabajo_docente.go
- models/data/plan_trabajo_docente.go
> feat: udistrital/sga_cliente#1432 Actualizado controlador para copiar carga del plan con colocación del servicio Horario

- controllers/plan_estudios.go
- swagger/swagger.json
- swagger/swagger.yml
> feat: udistrital/sga_cliente#1462 Agregado controlador para consulta de planes por tercero id

- controllers/plan_trabajo_docente.go
- routers/commentsRouter_controllers.go
- https://github.com/udistrital/sga_cliente/issues/1465
- https://github.com/udistrital/sga_cliente/issues/1478
> feat: udistrital/sga_cliente#1465 udistrital/sga_cliente#1478, ajuste asignacion docente a espacio academico modular

- controllers/plan_trabajo_docente.go
- controllers/reportes.go
- models/data/horarios.go
- https://github.com/udistrital/sga_cliente/issues/1483
> feat: udistrital/sga_cliente#1483 carga actividades en guardado ptd y generacion reporte

- controllers/plan_estudios.go
- process/plan_estudio_visualizacion_documento/plan_estudio_visualizacion_documento.go
feat: udistrital/sga_cliente#1472
- Se actualiza endpoint de generación de estructura de datos para visualizar el plan de estudios (JSON)
- Actualizado endpoint de generación de plan de estudios visual en pdf con colores
- Corregido total de créditos del pdf
- Corregido valor de estado de aprobación al crear plan de estudios
> feat: udistrital/sga_cliente#1472 Actualizado endpoints para generación y pintando del plan de estudios

- controllers/generar_recibo.go
- controllers/inscripciones.go
- swagger/swagger.yml
- tests/mid_test.go
- utils/meses_nombres.go
- utils/notificacion_service.go
udistrital/sga_cliente#1458
udistrital/sga_cliente#1471
> Merge from Feature/email notificaciones to develop

- utils/notificacion_service.go
fix: se cambia la función de envío de correo para evitar el error
> fix: se cambia la función de envío de correo para evitar el error

- controllers/plan_trabajo_docente.go
- https://github.com/udistrital/sga_cliente/issues/1484
- https://github.com/udistrital/sga_cliente/issues/1502
> feat: udistrital/sga_cliente#1484 udistrital/sga_cliente#1502 ajuste consulta PTD para indicar planes relacionados

- controllers/espacios_academicos.go
- utils/syllabus_functions.go
fix: ajuste estructura de generación templates con lambdas en Go del syllabus
> fix: ajuste estructura de generación templates con lambdas en Go del syllabus

- controllers/plan_trabajo_docente.go
- routers/commentsRouter_controllers.go
- swagger/swagger.json
- swagger/swagger.yml
- https://github.com/udistrital/sga_documentacion/issues/37
⚠️ Requiere actualizar swagger por syllabus ?
> feat: corrección endpoint disponibilidad espacios

- controllers/crear_proyecto_academico.go
- main.go
- https://github.com/udistrital/sga_documentacion/issues/133
> hotfix: udistrital/sga_documentacion#133 removed post to oikos

- controllers/espacios_academicos.go
- Ajuste para generar pdf en syllabus
---
udistrital/sga_documentacion#203
> fix: Ajuste para generar pdf de syllabus

- controllers/espacios_academicos.go
- controllers/reportes.go
management: Ajuste para generar pdf de syllabus
> management: Ajuste para generar pdf de syllabus

- controllers/espacios_academicos_legacy.go
- Ajuste en el endpoint SyllabusLegacy para asignar el valor de "cod_plan_estudio" en el json que retorna el controlador.
---
udistrital/sga_documentacion#203
> fix: Ajuste en el endpoint SyllabusLegacy

- controllers/espacios_academicos.go
- controllers/espacios_academicos_legacy.go
management: Ajuste en el endpoint SyllabusLegacy
> management: Ajuste en el endpoint SyllabusLegacy

- helpers/utilidades.go
udistrital/sga_documentacion#203
> Fix: Corregir manejo de valores nulos en DefaultToMapString

- controllers/espacios_academicos_legacy.go
- helpers/utilidades.go
management: Corregir manejo de valores nulos en DefaultToMapString
> management: Corregir manejo de valores nulos en DefaultToMapString

- controllers/inscripciones.go
- udistrital/sga_documentacion#266
> fix: udistrital/sga_documentacion#266 inclusión codigo interno generacion recibo

- controllers/inscripciones.go
Se arregla el codigo del programa que se envia para crear el recibo
> fix: codigo programa

- conf/app.conf
- controllers/inscripciones.go
udistrital/sga_documentacion/issues/273
> feat: Se incluye validación del código del proyecto coincide con el homologado por el SNIES

- controllers/inscripciones.go
udistrital/sga_documentacion#331
> Se omite propagar error cuando falta algun dato de terceros

- controllers/inscripciones.go
- udistrital/sga_documentacion#413
> fix: udistrital/sga_documentacion#413 Ajusta consulta parametros anio anterior si periodo es 1

- controllers/generar_recibo.go
- udistrital/sga_documentacion#413
> fix: udistrital/sga_documentacion#413 Ajusta zona horaria Bogota

- .drone.yml
se cambia a version especifica de imagen ecr y se cambia version de go
> fix: paso publish_to_ecr version imagen

- conf/app.conf
- controllers/facturacion_electronica.go
- routers/commentsRouter_controllers.go
- routers/router.go
Cambio asociado al issue #1591 de sga_cliente relacionado con el formulario de facturacion electronica.
> feat: Creacion de controlador del servicio JBPM para facturacion electronica en SGA V2

- controllers/generar_recibo.go
Por peticion de tesoreria se cambia la leyenda ubicada en la seccion de observaciones de los recibos de pago.
> feat: Cambio leyenda recibo de pago
